//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROCESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPROCESS()
        {
            this.TBLPENALTIES = new HashSet<TBLPENALTIES>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<byte> Employee { get; set; }
        public Nullable<System.DateTime> DATEOFPURCHASE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public Nullable<bool> ProcessState { get; set; }
        public Nullable<System.DateTime> BorrowBack { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLEMPLOYEE TBLEMPLOYEE { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPENALTIES> TBLPENALTIES { get; set; }
    }
}
