//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUNIVERSITIES
    {
        public int uni_id { get; set; }
        public string uni_name { get; set; }
        public Nullable<int> province_İD { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
